### ISSUE TITLE
Sub Commands

### ISSUE THREAD

**Issue by pocallaghan** [steverobbins/magescan#113]
How would you feel about each check being moved to it's own command so you could run them individually if required. `scan:modules`, `scan:unreachable` etc. Obviously we'd still keep `scan`, only it would become a meta command that proxies to all sub-commands, rather than containing all the logic itself.

**Comment by steverobbins** [comment]
I agree this is needed.  Didn't really plan for it when I first started development.

We would also add a `scan:all`

**Comment by pocallaghan** [comment]
Had a stab at this #114. Please note I only gave it minimal testing.
