### ISSUE TITLE
hang while scan website for magento version

### ISSUE THREAD

**Issue by prasadvibhakar** [steverobbins/magescan#143]
I have executed bin/magescan scan:version 2020llc.com, But its hang. I have tried to change CURLOPT_CONNECTTIMEOUT from 150 to 10, No luck. If the site is not responding or slow, then I think it's come out from the command prompt, but it is not working.

Other website it is working such as 
bin/magescan scan:version dinntrophy.com

                       
  Magento Information  
                       

+-----------+------------+
| Parameter | Value      |
+-----------+------------+
| Edition   | Enterprise |
| Version   | 1.13.0.2   |
+-----------+------------+

**Comment by steverobbins** [comment]
Some sites can't handle the crawling.  Doesn't seem to be an issue with this project.
