### ISSUE TITLE
self-update failing

### ISSUE THREAD

**Issue by exploresecurity** [steverobbins/magescan#153]
Thanks for creating this tool. But the "self-update" command fails as magescan.steverobbins.com does not resolve to an IP address.

**Comment by steverobbins** [comment]
"Fixed"

This project has been downgraded in my list of priorities so I'm not going to host the phar.  You'll just have to use Github ¯\\\_(ツ\)_/¯

**Comment by exploresecurity** [comment]
Fair enough. But it's probably worth removing the .phar installation option from README to save further queries!
