### ISSUE TITLE
Name change, composer replace

### ISSUE THREAD

**Issue by pocallaghan** [steverobbins/magescan#48]
With the package having a new name, might be an idea to add a [replace](https://getcomposer.org/doc/04-schema.md#replace) section into the composer file in case anybody depended on your original package.

```json
"replace": {
    "steverobbins/magento-guest-audit": "*"
}
```

Due to the nature of your tool, might not be a big deal, but thought I'd mention it.

**Comment by steverobbins** [comment]
:+1:
