### ISSUE TITLE
Check for Stores

### ISSUE THREAD

**Issue by rossmc** [steverobbins/magescan#85]
Hi @steverobbins This is more of a question rather than an issue.

I was wondering if there is a way of detecting what and how many stores & store views a site is using? Maybe even websites?  I was looking on the frontend end for any reference to  `__store` in the html and also to see if there was a **store cookie**,  sometimes I find them but often I do not.  I wonder if there are any other clues.

It would be useful info to have when comparing your site architecture with competitors.  Anyway great tool, thanks :)

**Comment by steverobbins** [comment]
The only method I can think of would be to look for the language selector dropdown, which has the `___store` params, but like you said it's often not used.
