### ISSUE TITLE
Can you add Magento 2 support when it launches?

### ISSUE THREAD

**Issue by choukalos** [steverobbins/magescan#88]
Can you add Magento 2 support when it launches ( Q4 this year )?

Thanks!

**Comment by steverobbins** [comment]
I plan to.  It may take some time though, I'm not as familiar with M2 as I am with M1

**Comment by cags** [comment]
With M2 now officially out, what is the plan? To add support to existing scans where possible (e.g. checking magento_version/index/index for version information), to branch off and create a separate branch / fork specific to M2 or to create separate commands within the main branch? As I'm going to be attempting to look into M2 over the coming months I'm happy to make pull requests, just looking for an idea of direction you'd prefer.

**Comment by steverobbins** [comment]
I added MD5 checks a little while ago: https://github.com/steverobbins/magento-version-identification-php/commit/60ecc9a9c0c6aed01bf41806334eebed8ea0f192

Not sure how accurate it's going to be with the new static content deployment method.

I didn't know about that controller.  Pretty convenient (though bad for security).  If you want to contribute just send a PR to the dev branch.  There are no immediate plans to separate out things for M2.

**Comment by cags** [comment]
I only came across it whilst taking a quick peak at some of the controllers in M2. It should be reliable (assuming it's not blocked), however it is not going to be 100% accurate. For security purposes it strips the end portions of the version number.
